### ISSUE TITLE
Error when getting user profile pic

### ISSUE THREAD

**Issue by rod41732** [2110423-2019-2/sec3_RoomScrum-Back-End-#6]
step to reproduce 
1.please create a  user if not already
2. login as said user --> please remember the `userId` in response
3. upload profile with `/user/profile-pic` --> it will return 200
4. GET `/user/profile-pic/:id` -> 500 internal server error

**Comment by rod41732** [comment]
test comment afbc761

**Comment by flapperz** [comment]
fixed in this commit afbc761

**Comment by rod41732** [comment]
OK fucking HAND
